# Generated by Django 5.0.6 on 2024-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees_required',
            field=models.BooleanField(default=False),
        ),
    ]
